apiVersion: v1
kind: ServiceAccount
metadata:
  name: katib-controller
  namespace: {{ .Values.kubeflow.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: katib-ui
  namespace: {{ .Values.kubeflow.namespace }}
---
