apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    app.kubernetes.io/name: poddefaults
  name: admission-webhook-service-account
  namespace: {{ .Values.kubeflow.namespace }}
