---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tensorboards-web-app-cluster-role
rules:
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - tensorboard.kubeflow.org
  resources:
  - tensorboards
  - tensorboards/finalizers
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: 'true'
  name: tensorboards-web-app-kubeflow-tensorboard-ui-admin
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: 'true'
  name: tensorboards-web-app-kubeflow-tensorboard-ui-edit
rules:
- apiGroups:
  - tensorboard.kubeflow.org
  resources:
  - tensorboards
  - tensorboards/finalizers
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: 'true'
  name: tensorboards-web-app-kubeflow-tensorboard-ui-view
rules:
- apiGroups:
  - tensorboard.kubeflow.org
  resources:
  - tensorboards
  - tensorboards/finalizers
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - get
  - list
  - watch

