apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tensorboards-web-app
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  host: tensorboards-web-app-service.{{ .Values.kubeflow.namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
