apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tensorboards-web-app-tensorboards-web-app
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  gateways:
  - {{ .Values.ingress.namespace }}/{{ .Values.ingress.gateway }}
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /tensorboards
    match:
    - uri:
        prefix: /tensorboards/
    rewrite:
      uri: /
    route:
    - destination:
        host: tensorboards-web-app-service.{{ .Values.kubeflow.namespace }}.svc.cluster.local
        port:
          number: 80
