apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-operator
  namespace: {{ .Values.namespace }}
  labels:
    control-plane: kubeflow-training-operator
spec:
  selector:
    matchLabels:
      control-plane: kubeflow-training-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: kubeflow-training-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - command:
            - /manager
          args:
          - --enable-scheme=tfjob
          - --enable-scheme=pytorchjob
          - --enable-scheme=mxjob
          - --enable-scheme=paddlejob
          - --enable-scheme=xgboostjob
          image: kubeflow/training-operator:v1-98d40be
          name: training-operator
          ports:
            - containerPort: 8080
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
      serviceAccountName: training-operator
      terminationGracePeriodSeconds: 10
