apiVersion: v1
data:
  ISTIO_GATEWAY: {{ .Values.ingress.namespace }}/{{ .Values.ingress.gateway }}
  RWO_PVC_SCHEDULING: 'True'
  TENSORBOARD_IMAGE: tensorflow/tensorflow:2.12.0
kind: ConfigMap
metadata:
  name: tensorboard-controller-config
  namespace: {{ .Values.kubeflow.namespace }}
