apiVersion: v1
kind: Service
metadata:
  labels:
    app: tensorboard-controller
    control-plane: tensorboard-controller-manager
  name: tensorboard-controller-manager-metrics-service
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: tensorboard-controller
    control-plane: tensorboard-controller-manager
