apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: {{ .Values.user.profile }}
spec:
  owner:
    kind: User
    name: {{ .Values.user.email }}
  {{- if .Values.awsIamForServiceAccount.awsIamRole }}
  plugins:
  - kind: AwsIamForServiceAccount
    spec:
      awsIamRole: '{{ .Values.awsIamForServiceAccount.awsIamRole }}'
      annotateOnly: true
  {{- end }}