---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: pvcviewer-controller-manager
  name: pvcviewer-webhook-service
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: pvcviewer-controller-manager
---