apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-notebooks-webapp-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-notebooks-webapp-cluster-role
subjects:
- kind: ServiceAccount
  name: kubeflow-notebooks-webapp-service-account
  namespace: {{ .Values.kubeflow.namespace }}
