apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kubeflow-notebooks-webapp
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  host: kubeflow-notebooks-webapp-service.{{ .Values.kubeflow.namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
