apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: kubeflow-notebooks-webapp-jupyter-notebook-role-binding
  namespace: {{ .Values.kubeflow.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeflow-notebooks-webapp-jupyter-notebook-role
subjects:
- kind: ServiceAccount
  name: jupyter-notebook
