apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubeflow-notebooks-webapp
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  gateways:
  - {{ .Values.ingress.namespace }}/{{ .Values.ingress.gateway }}
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /jupyter
    match:
    - uri:
        prefix: /jupyter/
    rewrite:
      uri: /
    route:
    - destination:
        host: kubeflow-notebooks-webapp-service.{{ .Values.kubeflow.namespace }}.svc.cluster.local
        port:
          number: 80
