apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: profiles
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.profile_controller.role_arn }}
  name: profiles-controller-service-account
  namespace: {{ .Values.kubeflow.namespace }}
