apiVersion: v1
kind: Service
metadata:
  name: notebook-controller-service
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  ports:
  - port: 443
    name: https
  selector:
    control-plane: notebook-controller
