apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-web-app-viewer-spec
  namespace: {{ .Values.kubeflow.namespace }}
data:
  viewer-spec.yaml : | 
    podTemplate:
      containers:
        - name: main
          image: $VOLUME_VIEWER_IMAGE
          env:
            - name: FB_ADDRESS
              value: "0.0.0.0"
            - name: FB_PORT
              value: "8080"
            - name: FB_DATABASE
              value: /tmp/filebrowser.db
            - name: FB_NOAUTH
              value: "true"
            - name: FB_BASEURL
              value: /pvcviewers/$NAMESPACE/$NAME/
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          # viewer-volume is provided automatically by the volumes web app
          volumeMounts:
            - name: viewer-volume
              mountPath: /data
          workingDir: /data
          serviceAccountName: default-editor
    networking:
      targetPort: 8080
      basePrefix: "/pvcviewers"
      rewrite: "/"
      timeout: 30s
    rwoScheduling: true