apiVersion: v1
kind: Service
metadata:
  labels:
    app: volumes-web-app
    run: volumes-web-app
  name: volumes-web-app-service
  namespace: {{ .Values.kubeflow.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: volumes-web-app
  type: ClusterIP
